### ISSUE TITLE
Missing content in slide pages

### ISSUE THREAD

**Issue by jkomyno** [serras/bob2021-mu#1]
Hi, thank you for these slides.
It seems that the bodies of pages 24, 25, 35 are missing.

**Comment by serras** [comment]
Oh, this is still a work in progress. The presentation is going to take place in 2 weeks as part of [BOB 2021](https://bobkonf.de/2021/en/). But developing in the open allows me to gather feedback and to use GitHub pages for rendering.

**Comment by jkomyno** [comment]
I'm sorry, I thought you already presented the slides lol. I'm looking forward to seeing the finished product.
Best of luck.
